language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

install:
  - travis_retry yarn install

script:
  - yarn test

after_success:
  - yarn codecov
cache: yarn
notifications:
  email: false
