language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"

install:
  - travis_retry yarn

script:
  - yarn test

after_success:
  - yarn codecov
  - yarn global add travis-deploy-once
  - travis-deploy-once "npm run semantic-release"

cache:
  directories: ~/.npm
notifications:
  email: false
