language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"

  install:
  - travis_retry yarn

script:
  - yarn test

after_success:
  - yarn codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
